### ISSUE TITLE
Non Antlers use

### ISSUE THREAD

**Issue by SuryaWebfox** [ArtemDanilov/flexipic#1]
How would one go about using this plugin in a non Antlers context? I would like to use this with a React front end.

**Comment by ArtemDanilov** [comment]
Hi!

This addon is primarily designed for use in Statamic projects with Antlers and Blade templates. If you want to use it with React in a Statamic project, you should create an API endpoint to expose the addon's data and then fetch this data in your React components.

Unfortunately, you can't use this addon in a pure Laravel project because it relies on Statamic's Glide methods to generate images. These methods are specific to Statamic and are not available in a standard Laravel setup.

In the near future, I plan to extend this addon's functionality to be compatible with Laravel projects.
